export type CourseListItem = {
  id: string
  title: string
  category: string
  thumbnail: string
  instructor: {
    name: string
    avatarUrl: string
    title: string
  }
  rating: number
  ratingCount: number
  price: string
  duration: string
  level: 'Beginner' | 'Intermediate' | 'Advanced'
  href: string
}

export type CourseDetailLesson = {
  id: string
  title: string
  duration: string
  type: 'video' | 'resource' | 'quiz'
  completed?: boolean
  locked?: boolean
}

export type CourseDetailModule = {
  id: string
  title: string
  duration: string
  lessons: CourseDetailLesson[]
}

export type CourseDetailInstructor = {
  id: string
  name: string
  title: string
  bio: string
  avatar: string
  students: number
}

export interface CourseDetailData {
  id: string
  title: string
  description: string
  thumbnail: string
  videoUrl: string
  instructor: CourseDetailInstructor
  price: string
  rating: number
  ratingCount: number
  studentCount: number
  duration: string
  level: 'Beginner' | 'Intermediate' | 'Advanced'
  category: string
  tags: string[]
  modules: CourseDetailModule[]
  enrolled?: boolean
  progress?: number
}

export const courseCatalog: CourseListItem[] = [
  {
    id: 'networking-system-security',
    title: 'Networking and System Security Installation',
    category: 'Technology',
    thumbnail: '/assets/course-thumbnails/Networking_result.webp',
    instructor: {
      name: 'Lukman Lukman',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lukman',
      title: 'Network Specialist',
    },
    rating: 4.9,
    ratingCount: 421,
    price: 'Contact for pricing',
    duration: '6 months',
    level: 'Intermediate',
    href: '/courses/description/networking-system-security',
  },
  {
    id: 'website-design-development',
    title: 'Website Design & Development',
    category: 'Web Development',
    thumbnail: '/assets/course-thumbnails/web-design_result.webp',
    instructor: {
      name: 'Lukman Lukman',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=WebDev',
      title: 'Web Designer',
    },
    rating: 4.8,
    ratingCount: 368,
    price: 'Contact for pricing',
    duration: '4 months',
    level: 'Beginner',
    href: '/courses/description/website-design-development',
  },
  {
    id: 'mobile-phone-repair',
    title: 'Mobile Phone Repair',
    category: 'Electronics',
    thumbnail: '/assets/course-thumbnails/mobile-repair_result.webp',
    instructor: {
      name: 'Ashiru Ahamd Rufai',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ashiru',
      title: 'Mobile Repair Expert',
    },
    rating: 4.7,
    ratingCount: 303,
    price: 'Contact for pricing',
    duration: '3 months',
    level: 'Beginner',
    href: '/courses/description/mobile-phone-repair',
  },
  {
    id: 'electrical-installations',
    title: 'Electrical Installations',
    category: 'Engineering',
    thumbnail: '/assets/course-thumbnails/electrical_result.webp',
    instructor: {
      name: 'Idris Shuaibu',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Idris',
      title: 'Electrical Trainer',
    },
    rating: 4.8,
    ratingCount: 254,
    price: 'Contact for pricing',
    duration: '6 months',
    level: 'Intermediate',
    href: '/courses/description/electrical-installations',
  },
  {
    id: 'furniture-making',
    title: 'Furniture Making',
    category: 'Craftsmanship',
    thumbnail: '/assets/course-thumbnails/furniture_result.webp',
    instructor: {
      name: 'Fatima Bello',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
      title: 'Woodworking Coach',
    },
    rating: 4.7,
    ratingCount: 197,
    price: 'Contact for pricing',
    duration: '5 months',
    level: 'Intermediate',
    href: '/courses/description/furniture-making',
  },
  {
    id: 'painting-decoration',
    title: 'Painting, Decoration & Finishes (Interior Design)',
    category: 'Arts & Design',
    thumbnail: '/assets/course-thumbnails/painting_result.webp',
    instructor: {
      name: 'Abdullahi Muhammad',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abdullahi',
      title: 'Design Specialist',
    },
    rating: 4.6,
    ratingCount: 184,
    price: 'Contact for pricing',
    duration: '4 months',
    level: 'Beginner',
    href: '/courses/description/painting-decoration',
  },
  {
    id: 'wood-work',
    title: 'Wood Work',
    category: 'Craftsmanship',
    thumbnail: '/assets/course-thumbnails/woodwork_result.webp',
    instructor: {
      name: 'Ibrahim Yusuf',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ibrahim',
      title: 'Carpentry Specialist',
    },
    rating: 4.7,
    ratingCount: 210,
    price: 'Contact for pricing',
    duration: '4 months',
    level: 'Beginner',
    href: '/courses/description/wood-work',
  },
  {
    id: 'upholstery',
    title: 'Upholstery',
    category: 'Craftsmanship',
    thumbnail: '/assets/course-thumbnails/upholstery_result.webp',
    instructor: {
      name: 'Maryam Suleiman',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maryam',
      title: 'Interior Upholsterer',
    },
    rating: 4.6,
    ratingCount: 176,
    price: 'Contact for pricing',
    duration: '3 months',
    level: 'Beginner',
    href: '/courses/description/upholstery',
  },
  {
    id: 'bricklaying-concreting',
    title: 'Bricklaying, Block laying, Concreting And Interlocking',
    category: 'Construction',
    thumbnail: '/assets/course-thumbnails/bricklaying_result.webp',
    instructor: {
      name: 'Abdullahi Musa',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AbdullahiM',
      title: 'Construction Lead',
    },
    rating: 4.8,
    ratingCount: 239,
    price: 'Contact for pricing',
    duration: '6 months',
    level: 'Intermediate',
    href: '/courses/description/bricklaying-concreting',
  },
  {
    id: 'plumbing-pipe-fitting',
    title: 'Plumbing & Pipe Fitting',
    category: 'Engineering',
    thumbnail: '/assets/course-thumbnails/plumbing_result.webp',
    instructor: {
      name: 'Salisu Lawal',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Salisu',
      title: 'Plumbing Expert',
    },
    rating: 4.7,
    ratingCount: 197,
    price: 'Contact for pricing',
    duration: '5 months',
    level: 'Intermediate',
    href: '/courses/description/plumbing-pipe-fitting',
  },
  {
    id: 'hospitality-catering',
    title: 'Hospitality & Catering',
    category: 'Service',
    thumbnail: '/assets/course-thumbnails/hospitality_result.webp',
    instructor: {
      name: 'Fateema Garba Suleiman',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fateema',
      title: 'Hospitality Coach',
    },
    rating: 4.5,
    ratingCount: 156,
    price: 'Contact for pricing',
    duration: '4 months',
    level: 'Beginner',
    href: '/courses/description/hospitality-catering',
  },
  {
    id: 'cosmetology-beauty',
    title: 'Cosmetology & Beauty Therapy',
    category: 'Beauty & Wellness',
    thumbnail: '/assets/course-thumbnails/cosmetology_result.webp',
    instructor: {
      name: "Sa'adatu Muhammad",
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Saadatu',
      title: 'Beauty Specialist',
    },
    rating: 4.6,
    ratingCount: 184,
    price: 'Contact for pricing',
    duration: '4 months',
    level: 'Beginner',
    href: '/courses/description/cosmetology-beauty',
  },
  {
    id: 'fashion-design',
    title: 'Fashion Design & Garment Making',
    category: 'Arts & Design',
    thumbnail: '/assets/course-thumbnails/fashion_result.webp',
    instructor: {
      name: 'Hauwakulu Muhammad',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hauwakulu',
      title: 'Fashion Designer',
    },
    rating: 4.5,
    ratingCount: 162,
    price: 'Contact for pricing',
    duration: '5 months',
    level: 'Beginner',
    href: '/courses/description/fashion-design',
  },
  {
    id: 'hardware-maintenance',
    title: 'Hardware Maintenance',
    category: 'Technology',
    thumbnail: '/assets/course-thumbnails/hardware_result.webp',
    instructor: {
      name: 'Ashiru Ahmad',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AshiruA',
      title: 'Tech Repair Lead',
    },
    rating: 4.7,
    ratingCount: 180,
    price: 'Contact for pricing',
    duration: '3 months',
    level: 'Beginner',
    href: '/courses/description/hardware-maintenance',
  },
  {
    id: 'welding-fabrication',
    title: 'Welding And Fabrication',
    category: 'Engineering',
    thumbnail: '/assets/course-thumbnails/welding_result.webp',
    instructor: {
      name: 'Damilola John',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Damilola',
      title: 'Fabrication Trainer',
    },
    rating: 4.8,
    ratingCount: 212,
    price: 'Contact for pricing',
    duration: '5 months',
    level: 'Intermediate',
    href: '/courses/description/welding-fabrication',
  },
  {
    id: 'home-electrical-appliances',
    title: 'Home Electrical Appliances',
    category: 'Electronics',
    thumbnail: '/assets/course-thumbnails/appliances_result.webp',
    instructor: {
      name: 'Idris Shuaibu',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=IdrisE',
      title: 'Appliance Technician',
    },
    rating: 4.6,
    ratingCount: 143,
    price: 'Contact for pricing',
    duration: '3 months',
    level: 'Beginner',
    href: '/courses/description/home-electrical-appliances',
  },
  {
    id: 'aluminium-fabrication',
    title: 'Aluminium Fabrication',
    category: 'Engineering',
    thumbnail: '/assets/course-thumbnails/aluminium_result.webp',
    instructor: {
      name: 'Umar Farouk',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Umar',
      title: 'Metal Fabricator',
    },
    rating: 4.7,
    ratingCount: 169,
    price: 'Contact for pricing',
    duration: '4 months',
    level: 'Intermediate',
    href: '/courses/description/aluminium-fabrication',
  },
]

export const categories = [
  'All',
  'Technology',
  'Web Development',
  'Electronics',
  'Engineering',
  'Craftsmanship',
  'Arts & Design',
  'Construction',
  'Service',
  'Beauty & Wellness',
]

export const levels = ['All', 'Beginner', 'Intermediate', 'Advanced']

const baseModules: CourseDetailModule[] = [
  {
    id: 'mod1',
    title: 'Foundations and safety standards',
    duration: '3 weeks',
    lessons: [
      { id: 'les1', title: 'Core principles overview', duration: '45 min', type: 'video' },
      { id: 'les2', title: 'Certification standards', duration: '1 hr', type: 'video', completed: true },
      { id: 'les3', title: 'Practical safety checklist', duration: '30 min', type: 'resource' },
    ],
  },
  {
    id: 'mod2',
    title: 'Hands-on installation & repair',
    duration: '4 weeks',
    lessons: [
      { id: 'les4', title: 'Hands-on lab session', duration: '1.5 hrs', type: 'video' },
      { id: 'les5', title: 'Troubleshooting techniques', duration: '1 hr', type: 'video' },
      { id: 'les6', title: 'Field practice workbook', duration: '45 min', type: 'resource' },
    ],
  },
  {
    id: 'mod3',
    title: 'Certification preparation',
    duration: '3 weeks',
    lessons: [
      { id: 'les7', title: 'Exam readiness', duration: '1 hr', type: 'video', locked: true },
      { id: 'les8', title: 'Mock assessment', duration: '1.5 hrs', type: 'quiz', locked: true },
      { id: 'les9', title: 'Industry project', duration: '2 hrs', type: 'resource', locked: true },
    ],
  },
]

export const courseDetails: Record<string, CourseDetailData> = {
  'networking-system-security': {
    id: 'networking-system-security',
    title: 'Networking and System Security Installation',
    description:
      'Learn modern networking, secure installation, and access controls with a practical focus on real workplace deployments and NBTE certification readiness.',
    thumbnail: '/assets/course-thumbnails/Networking_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'lukman',
      name: 'Lukman Lukman',
      title: 'Network Specialist',
      bio: 'Lukman combines enterprise networking experience with practical cyber-security training for entry-level technicians.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lukman',
      students: 1987,
    },
    price: 'Contact for pricing',
    rating: 4.9,
    ratingCount: 421,
    studentCount: 2560,
    duration: '6 months',
    level: 'Intermediate',
    category: 'Technology',
    tags: ['NSQ Certified', 'Hands-on', 'Security'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'website-design-development': {
    id: 'website-design-development',
    title: 'Website Design & Development',
    description:
      'Build responsive, modern websites with practical design systems, HTML/CSS, JavaScript, and deployment workflows for business-ready digital studios.',
    thumbnail: '/assets/course-thumbnails/web-design_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'webdev',
      name: 'Lukman Lukman',
      title: 'Web Designer',
      bio: 'Lukman has designed websites for startups and corporate brands, teaching students design thinking and development best practices.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=WebDev',
      students: 2314,
    },
    price: 'Contact for pricing',
    rating: 4.8,
    ratingCount: 368,
    studentCount: 2892,
    duration: '4 months',
    level: 'Beginner',
    category: 'Web Development',
    tags: ['NSQ Certified', 'Portfolio Ready', 'Practical'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'mobile-phone-repair': {
    id: 'mobile-phone-repair',
    title: 'Mobile Phone Repair',
    description:
      'Master mobile phone repair, diagnostics, and assembly with hands-on labs that prepare you for service roles across retail and repair shops.',
    thumbnail: '/assets/course-thumbnails/mobile-repair_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'ashiru',
      name: 'Ashiru Ahamd Rufai',
      title: 'Mobile Repair Expert',
      bio: 'Ashiru has trained hundreds of technicians in practical handset repair, fault-finding, and customer service for retail environments.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ashiru',
      students: 1750,
    },
    price: 'Contact for pricing',
    rating: 4.7,
    ratingCount: 303,
    studentCount: 2440,
    duration: '3 months',
    level: 'Beginner',
    category: 'Electronics',
    tags: ['NBTE Approved', 'Practical', 'Job-ready'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'electrical-installations': {
    id: 'electrical-installations',
    title: 'Electrical Installations',
    description:
      'Learn electrical wiring, installations, and systems troubleshooting with industry-aligned training for residential and commercial projects.',
    thumbnail: '/assets/course-thumbnails/electrical_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'idris',
      name: 'Idris Shuaibu',
      title: 'Electrical Trainer',
      bio: 'Idris delivers practical electrical courses focusing on safe installations, compliance, and career-ready hands-on practice.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Idris',
      students: 1880,
    },
    price: 'Contact for pricing',
    rating: 4.8,
    ratingCount: 254,
    studentCount: 2195,
    duration: '6 months',
    level: 'Intermediate',
    category: 'Engineering',
    tags: ['NSQ Certified', 'Field Skills', 'Safety First'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'furniture-making': {
    id: 'furniture-making',
    title: 'Furniture Making',
    description:
      'Train in furniture design, wood joinery, finishing, and production workflows for resilient craftsmanship and interior fit-outs.',
    thumbnail: '/assets/course-thumbnails/furniture_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'fatima',
      name: 'Fatima Bello',
      title: 'Woodworking Coach',
      bio: 'Fatima teaches woodworking fundamentals and practical workshop processes for students building furniture and fittings.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
      students: 1632,
    },
    price: 'Contact for pricing',
    rating: 4.7,
    ratingCount: 197,
    studentCount: 2010,
    duration: '5 months',
    level: 'Intermediate',
    category: 'Craftsmanship',
    tags: ['Practical', 'Quality Finish', 'NBTE Ready'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'painting-decoration': {
    id: 'painting-decoration',
    title: 'Painting, Decoration & Finishes (Interior Design)',
    description:
      'Develop painting, finishing, and creative décor skills for interior environments, with studio practice on surface preparation and finishes.',
    thumbnail: '/assets/course-thumbnails/painting_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'abdullahi',
      name: 'Abdullahi Muhammad',
      title: 'Design Specialist',
      bio: 'Abdullahi combines decorative art with commercial finish techniques for modern interiors and small-business decorators.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abdullahi',
      students: 1440,
    },
    price: 'Contact for pricing',
    rating: 4.6,
    ratingCount: 184,
    studentCount: 1953,
    duration: '4 months',
    level: 'Beginner',
    category: 'Arts & Design',
    tags: ['Creative', 'NSQ Approved', 'Practical'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'wood-work': {
    id: 'wood-work',
    title: 'Wood Work',
    description:
      'Master accurate woodworking, joinery, and finishing techniques through practical shop sessions and project-based learning.',
    thumbnail: '/assets/course-thumbnails/woodwork_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'ibrahim',
      name: 'Ibrahim Yusuf',
      title: 'Carpentry Specialist',
      bio: 'Ibrahim has trained craftsmen in carpentry and furniture production for commercial and residential workflows.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ibrahim',
      students: 1520,
    },
    price: 'Contact for pricing',
    rating: 4.7,
    ratingCount: 210,
    studentCount: 2084,
    duration: '4 months',
    level: 'Beginner',
    category: 'Craftsmanship',
    tags: ['Workshop', 'Hands-on', 'NSQ Certified'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'upholstery': {
    id: 'upholstery',
    title: 'Upholstery',
    description:
      'Learn upholstery skills from frame repairs to fabric finishes, with practical training for furniture and interior soft fittings.',
    thumbnail: '/assets/course-thumbnails/upholstery_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'maryam',
      name: 'Maryam Suleiman',
      title: 'Interior Upholsterer',
      bio: 'Maryam trains students in upholstery workflows, finishes, and production standards for interiors and furniture.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maryam',
      students: 1327,
    },
    price: 'Contact for pricing',
    rating: 4.6,
    ratingCount: 176,
    studentCount: 1788,
    duration: '3 months',
    level: 'Beginner',
    category: 'Craftsmanship',
    tags: ['Creative', 'Job Ready', 'Practical'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'bricklaying-concreting': {
    id: 'bricklaying-concreting',
    title: 'Bricklaying, Block laying, Concreting And Interlocking',
    description:
      'Gain construction skills in masonry, concreting, and interlocking systems for durable site-ready workmanship.',
    thumbnail: '/assets/course-thumbnails/bricklaying_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'abdullahi-m',
      name: 'Abdullahi Musa',
      title: 'Construction Lead',
      bio: 'Abdullahi trains learners in modern masonry and concreting practices for residential and commercial applications.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AbdullahiM',
      students: 1710,
    },
    price: 'Contact for pricing',
    rating: 4.8,
    ratingCount: 239,
    studentCount: 2205,
    duration: '6 months',
    level: 'Intermediate',
    category: 'Construction',
    tags: ['Site-ready', 'NBTE', 'Practical'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'plumbing-pipe-fitting': {
    id: 'plumbing-pipe-fitting',
    title: 'Plumbing & Pipe Fitting',
    description:
      'Practice plumbing installations, pipe fitting, leak diagnosis and repair with a strong emphasis on industry safety and quality standards.',
    thumbnail: '/assets/course-thumbnails/plumbing_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'salisu',
      name: 'Salisu Lawal',
      title: 'Plumbing Expert',
      bio: 'Salisu delivers practical plumbing training for building services and maintenance technicians.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Salisu',
      students: 1420,
    },
    price: 'Contact for pricing',
    rating: 4.7,
    ratingCount: 197,
    studentCount: 1900,
    duration: '5 months',
    level: 'Intermediate',
    category: 'Engineering',
    tags: ['Field Skills', 'NSQ Ready', 'Hands-on'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'hospitality-catering': {
    id: 'hospitality-catering',
    title: 'Hospitality & Catering',
    description:
      'Train in hospitality service, kitchen operations, and catering fundamentals for immediate roles in hotels, restaurants and event service.',
    thumbnail: '/assets/course-thumbnails/hospitality_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'fateema',
      name: 'Fateema Garba Suleiman',
      title: 'Hospitality Coach',
      bio: 'Fateema specializes in hospitality service training for students entering catering and guest experience roles.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fateema',
      students: 1488,
    },
    price: 'Contact for pricing',
    rating: 4.5,
    ratingCount: 156,
    studentCount: 1710,
    duration: '4 months',
    level: 'Beginner',
    category: 'Service',
    tags: ['Customer Service', 'Practical', 'Certification'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'cosmetology-beauty': {
    id: 'cosmetology-beauty',
    title: 'Cosmetology & Beauty Therapy',
    description:
      'Develop cosmetology skills for beauty therapy, skin treatments, and professional salon services with practical, client-focused training.',
    thumbnail: '/assets/course-thumbnails/cosmetology_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'saadatu',
      name: "Sa'adatu Muhammad",
      title: 'Beauty Specialist',
      bio: 'Sa’adatu trains learners in salon standards, beauty treatments, and client care for modern wellness careers.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Saadatu',
      students: 1590,
    },
    price: 'Contact for pricing',
    rating: 4.6,
    ratingCount: 184,
    studentCount: 1875,
    duration: '4 months',
    level: 'Beginner',
    category: 'Beauty & Wellness',
    tags: ['Beauty Therapy', 'NBTE', 'Practical'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'fashion-design': {
    id: 'fashion-design',
    title: 'Fashion Design & Garment Making',
    description:
      'Learn garment design, pattern making, and tailoring for fashion production with studio-based practical workshops.',
    thumbnail: '/assets/course-thumbnails/fashion_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'hauwakulu',
      name: 'Hauwakulu Muhammad',
      title: 'Fashion Designer',
      bio: 'Hauwakulu brings industry fashion design and tailoring expertise to practical student projects and portfolio building.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hauwakulu',
      students: 1340,
    },
    price: 'Contact for pricing',
    rating: 4.5,
    ratingCount: 162,
    studentCount: 1772,
    duration: '5 months',
    level: 'Beginner',
    category: 'Arts & Design',
    tags: ['Design', 'Production', 'Career-ready'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'hardware-maintenance': {
    id: 'hardware-maintenance',
    title: 'Hardware Maintenance',
    description:
      'Build practical hardware maintenance skills with PC, laptop, and peripheral repair training for service centers and support roles.',
    thumbnail: '/assets/course-thumbnails/hardware_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'ashiru-ahmad',
      name: 'Ashiru Ahmad',
      title: 'Tech Repair Lead',
      bio: 'Ashiru shares electronics and hardware care strategies for reliable device maintenance and support workflows.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AshiruA',
      students: 1635,
    },
    price: 'Contact for pricing',
    rating: 4.7,
    ratingCount: 180,
    studentCount: 1950,
    duration: '3 months',
    level: 'Beginner',
    category: 'Technology',
    tags: ['Repair', 'Career-ready', 'NBTE'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'welding-fabrication': {
    id: 'welding-fabrication',
    title: 'Welding And Fabrication',
    description:
      'Train in welding processes, fabrications, and metal finishing for industrial and construction applications.',
    thumbnail: '/assets/course-thumbnails/welding_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'damilola',
      name: 'Damilola John',
      title: 'Fabrication Trainer',
      bio: 'Damilola teaches welding and fabrication techniques used in production, construction, and metalworking trade jobs.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Damilola',
      students: 1702,
    },
    price: 'Contact for pricing',
    rating: 4.8,
    ratingCount: 212,
    studentCount: 2180,
    duration: '5 months',
    level: 'Intermediate',
    category: 'Engineering',
    tags: ['Metal Work', 'Hands-on', 'NSQ Certified'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'home-electrical-appliances': {
    id: 'home-electrical-appliances',
    title: 'Home Electrical Appliances',
    description:
      'Gain skills in appliance diagnostics, repair, and maintenance for household electrical devices and small appliances.',
    thumbnail: '/assets/course-thumbnails/appliances_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'idris-e',
      name: 'Idris Shuaibu',
      title: 'Appliance Technician',
      bio: 'Idris provides practical appliance repair instruction with a focus on safe service and customer-ready outcomes.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=IdrisE',
      students: 1584,
    },
    price: 'Contact for pricing',
    rating: 4.6,
    ratingCount: 143,
    studentCount: 1805,
    duration: '3 months',
    level: 'Beginner',
    category: 'Electronics',
    tags: ['Repair', 'Service', 'Practical'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
  'aluminium-fabrication': {
    id: 'aluminium-fabrication',
    title: 'Aluminium Fabrication',
    description:
      'Learn aluminium fabrication methods for window frames, structures, and finishing accents used in construction and interior design.',
    thumbnail: '/assets/course-thumbnails/aluminium_result.webp',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    instructor: {
      id: 'umar',
      name: 'Umar Farouk',
      title: 'Metal Fabricator',
      bio: 'Umar combines fabrication expertise with quality control standards for commercial and residential aluminium work.',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Umar',
      students: 1498,
    },
    price: 'Contact for pricing',
    rating: 4.7,
    ratingCount: 169,
    studentCount: 1840,
    duration: '4 months',
    level: 'Intermediate',
    category: 'Engineering',
    tags: ['Fabrication', 'NSQ', 'Career-ready'],
    modules: baseModules,
    enrolled: false,
    progress: 0,
  },
}
